const API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT;
const SOCKET_URL = process.env.NEXT_PUBLIC_SOCKET_API_ENDPOINT;
const HOSTNAME = process.env.NEXT_PUBLIC_HOSTNAME;

export { API_ENDPOINT, HOSTNAME, SOCKET_URL };
