const API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT;
const SOCKET_API = process.env.SOCKET_API_ENDPOINT;
const HOSTNAME = process.env.NEXT_PUBLIC_HOSTNAME;

export { API_ENDPOINT, HOSTNAME, SOCKET_API };
