import type { AppProps } from 'next/app';
import { ReactElement, ReactNode, Suspense, useState } from 'react';
import DefaultLayout from '../components/Layouts/DefaultLayout';
import { Provider } from 'react-redux';
import store from '../store/index';
import Head from 'next/head';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { appWithI18Next } from 'ni18n';
import { ni18nConfig } from 'ni18n.config.ts';
import 'react-perfect-scrollbar/dist/css/styles.css';
import '../styles/tailwind.css';
import '../styles/custom.css';
import '../styles/pagination.css';
//
import '../FileManager/FileCard/FileCard';
// import '../FileManager/FileExplorer/FileExplorer.css';

import { NextPage } from 'next';
import { AuthProvider } from '@/contexts/authContext';
import 'react-toastify/dist/ReactToastify.min.css';
export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

const App = ({ Component, pageProps }: AppPropsWithLayout) => {
  const getLayout = Component.getLayout ?? ((page) => <DefaultLayout>{page}</DefaultLayout>);

  return (
    <AuthProvider>
      <Provider store={store}>
        <Head>
          <title>BEIGE</title>
          <meta charSet="UTF-8" />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <ToastContainer />
        {getLayout(<Component {...pageProps} />)}
      </Provider>
    </AuthProvider>
  );
};
export default appWithI18Next(App, ni18nConfig);
